---
comment: using auto configuration to provide configuration of what to monitor in connections array
sensor:
  sensorId: 5bec19e8087d3020105b8890
  name: canary1
  created:
    when: 2018-11-14T20:05:17.393Z
    by: Lewczyk,John
synergyCheck:
  customerId: 5b8980bb9456dc0014456008
agent:
  agentId: 5beba29fbd539721b4c4744c
  autoConfig: true
  httpProtocol: http
  hostName: localhost
  port: 19999 # this agent listens on this port
  apiBase: /api/v1/
  apiKeys: # for sensors to authenticate with
  - fd3c36e1-fa93-438a-9f6e-5ef69427305a
  - 7da420a0-22e8-446b-97a4-2cfc84d72989
heartbeat: 30000
sendStats: true
